[package]
name = "stella2_windres"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]

[build-dependencies]
embed-resource = "1.3.0"
icon_baker = { path = "../../support/icon_baker" }
libflate = "0.1.27"

[lib]
path = "lib.rs"
